C-0052 - check access to cloud provider meta data API
kubescape/host-scanner pull request #18
Opened 2022-11-27 09:01 UTC by kooomix

## Describe your changes
Added "ProviderMetaDataAPIAccess" entry - if true, cloud provider meta data API has access from Node.

References:

**aws API metadata:**
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html
url to check :169.254.169.254/latest/meta-data/local-hostname

**Azure:**
https://learn.microsoft.com/en-us/azure/virtual-machines/windows/instance-metadata-service?tabs=windows
url to check: http://169.254.169.254/metadata/instance?api-version=2021-02-01
"headers": {"Metadata": "true"}

**Google:**
https://cloud.google.com/compute/docs/metadata/querying-metadata
url to check: http://169.254.169.254/computeMetadata/v1/?alt=json&recursive=true
"headers": {"Metadata-Flavor": "Google"}

## Checklist before requesting a review
- [V] My code follows the style guidelines of this project
- [V] I have commented my code, particularly in hard-to-understand areas
- [V] I have performed a self-review of my code
- [V] If it is a core feature, I have added thorough tests.
- [V] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

2022-11-27 14:59 UTC, shm12 commented on sensor/cloudProvider.go
> +	}
```suggestion
	requests := []struct {
		url     string
		headers map[string]string
	}{
		{
			"http://169.254.169.254/computeMetadata/v1/?alt=json&recursive=true",
			map[string]string{"Metadata-Flavor": "Google"},
		},
		{
			"http://169.254.169.254/metadata/instance?api-version=2021-02-01",
			map[string]string{"Metadata": "true"},
		},
		{
			"http://169.254.169.254/latest/meta-data/local-hostname",
			map[string]string{},
		},
	}

	for _,req := range requests {
		res, err := httputils.HttpGet(client, req.url, req.headers)

		if err == nil && res.StatusCode == 200 {
			return true
		}	
	}
```

2022-11-27 15:07 UTC, shm12 commented on sensor/cloudProvider.go
> +}
```suggestion
var MetaDataAPIRequests = []struct {
	url     string
	headers map[string]string
} 	{
	{
		"http://169.254.169.254/computeMetadata/v1/?alt=json&recursive=true",
		map[string]string{"Metadata-Flavor": "Google"},
	},
	{
		"http://169.254.169.254/metadata/instance?api-version=2021-02-01",
		map[string]string{"Metadata": "true"},
	},
	{
		"http://169.254.169.254/latest/meta-data/local-hostname",
		map[string]string{},
	},
}

func hasMetaDataAPIAccess() bool {
	client := &http.Client{}

	for _,req := range MetaDataAPIRequests {
		res, err := httputils.HttpGet(client, req.url, req.headers)

		if err == nil && res.StatusCode == 200 {
			return true
		}	
	}

	return false

}
```
And then you can unitest it

2022-11-27 15:07 UTC, shm12 requested changes
Please add unitests

2022-11-27 15:28 UTC, kooomix commented on sensor/cloudProvider.go
> +}
What is it that you think needed to unitest here? 
All request will anyway return false (no matter what the params are)...

2022-11-27 15:30 UTC, shm12 commented on sensor/cloudProvider.go
> +}
Everything needs unitets, so the coverage report will look good :)

2022-11-28 08:06 UTC, Bezbran requested changes

2022-11-28 08:06 UTC, Bezbran commented on sensor/cloudProvider.go
> +	client := &http.Client{}
In golang http client is an heavy resource.
We should create a global one (singleton) and use it.

2022-11-28 08:27 UTC, kooomix commented on sensor/cloudProvider.go
> +	client := &http.Client{}
An http client object is being instantiated only once (in the whole host-scanner).
Are you offering to use a global for cases we will want to re-use it in the future?

2022-11-28 11:56 UTC, shm12 commented on sensor/internal/utils/globals.go
> +	lock = &sync.Mutex{}
Please give a more meaningful name to the `lock` object

2022-11-28 11:56 UTC, shm12 commented on sensor/cloudProvider_test.go
> +	}{
Consider extracting the anonymous struct to named struct, so you don't have to redeclare the struct every time you create it

2022-11-28 12:09 UTC, kooomix commented on sensor/cloudProvider_test.go
> +	}{
done

2022-11-28 12:10 UTC, kooomix commented on sensor/internal/utils/globals.go
> +	lock = &sync.Mutex{}
done

2022-11-28 12:18 UTC, shm12 approved these changes

2022-11-28 12:48 UTC, Bezbran approved these changes

2022-11-28 12:49 UTC, merged