add otel with uptrace client
kubescape/host-scanner pull request #23
Opened 2023-01-18 14:59 UTC by matthyx

## Describe your changes

## Screenshots - If Any (Optional)

## Issue ticket number and link

## Checklist before requesting a review
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

2023-01-28 19:01 UTC, dwertent commented
@matthyx Is this PR ready for review?

2023-01-28 19:33 UTC, matthyx commented
No I want to get the full spans first

2023-01-30 06:53 UTC, dwertent requested changes

2023-01-30 06:53 UTC, dwertent commented on sensor.go
> +	// to enable otel, set OTEL_COLLECTOR_SVC=otel-collector:4317
[TODO]: Get accountID and OTEL svc from env

2023-01-30 08:03 UTC, matthyx commented on sensor/verboseutils_test.go
>  	observedLogger := zap.New(observedZapCore)
@dwertent the test failure comes from not being able to intercept the logger output... do you have any idea to fix that?

2023-01-30 15:49 UTC, matthyx commented
@dwertent ready for review!

2023-01-30 18:07 UTC, dwertent reviewed
Please review my changes. Nothing is blocking.

2023-01-30 18:07 UTC, dwertent commented on sensor.go
> +	zapLogger *otelzap.Logger
[Question]: Why are we using here the `zapLogger`?

2023-01-30 18:07 UTC, dwertent commented on sensor.go
> +	zapLogger = otelzap.New(l)
[TODO]: The error check should happen before the initialization

2023-01-30 18:07 UTC, dwertent commented on sensor.go
>  	fmt.Println("Host scanner service build version: " + BuildVersion)
```suggestion
	logger.L().Info("BuildVersion", helpers.String(BuildVersion))
```

2023-01-30 18:09 UTC, dwertent approved these changes
Please see my comment from the previous review, they are not blocking.

2023-01-30 18:09 UTC, merged