test: add e2e test local
kubescape/host-scanner pull request #44
Opened 2023-05-08 17:02 UTC by alegrey91

## Overview

2023-05-11 12:42 UTC, yuleib commented on .github/workflows/e2e-tests-local.yaml
> +  push:
consider of add pull_request also. We want to make sure during the dev. that e2e tests are passed

2023-05-11 12:42 UTC, yuleib commented on .github/workflows/e2e-tests-local.yaml
> +        #k8s-version: ['v1.25.0', 'v1.26.0', 'v1.27.0']
can we remove the comment ?

2023-05-11 12:43 UTC, yuleib commented on .github/workflows/e2e-tests-local.yaml
> +        uses: actions/checkout@v2
replace checkout to v3 please. v2 is old

2023-05-11 12:46 UTC, yuleib commented on deployment/k8s-deployment.yaml
> +        image: quay.io/kubescape/host-scanner:v1.0.57
why we chnaged this to default ? we should keep using the latest while we are building HS. doesn't we  ?

2023-05-11 17:09 UTC, alegrey91 commented on .github/workflows/e2e-tests-local.yaml
> +  push:
yes, `pull_request` event is currently commented to speed up local tests.
Once the PR will be ready, I'll remove the comments.

2023-05-11 17:10 UTC, alegrey91 commented on .github/workflows/e2e-tests-local.yaml
> +        #k8s-version: ['v1.25.0', 'v1.26.0', 'v1.27.0']
same as above.

2023-05-11 17:12 UTC, alegrey91 commented on deployment/k8s-deployment.yaml
> +        image: quay.io/kubescape/host-scanner:v1.0.57
yes, my fault. I uploaded the wrong file. Do we already have a tag `latest` for container image?

2023-05-11 17:13 UTC, alegrey91 commented on .github/workflows/e2e-tests-local.yaml
> +        uses: actions/checkout@v2
fixed

2023-05-28 09:13 UTC, yuleib requested changes
@alegrey91 Well done with PR, 
i've put a few comments to resolve before merging, also let's review it together since it's a very bug PR with a lot of chnages

2023-05-28 09:13 UTC, yuleib commented on deployment/host-scanner.yaml
> +      # this toleration is to have the DaemonDet runnable on all nodes (including masters)
```suggestion
      # this toleration is to have the DaemonSet runnable on all nodes (including masters)
```

2023-05-28 09:13 UTC, yuleib commented on deployment/host-scanner.yaml
>        - name: host-sensor
aren't we changing it into host-scanner ?

2023-05-28 09:13 UTC, yuleib commented on deployment/host-scanner.yaml
> +        image: kubescape/host-scanner:test
how we are pulling the latest host-scanner now ? 
something is not clreared to me on this file now

2023-05-28 09:13 UTC, yuleib commented on deployment/host-scanner.yaml
> +            cpu: 0.1m
are we sure about this ? how did you test this performance ?

2023-05-28 09:13 UTC, yuleib commented on e2e/cloudproviderinfo_test.go
> +		})
need to fix and resolve those failures

2023-05-28 09:13 UTC, yuleib commented on e2e/cniinfo_test.go
> +
need to fix and resolve those failures

2023-05-28 09:13 UTC, yuleib commented on e2e/cniinfo_test.go
> +			}
need to fix and resolve those failures

2023-05-29 07:30 UTC, alegrey91 commented on deployment/host-scanner.yaml
>        - name: host-sensor
I took it from [kubescape](https://github.com/kubescape/kubescape/blob/master/core/pkg/hostsensorutils/hostsensor.yaml#L32), so we can test `host-scanner` in the same way we deploy it on the cluster.

2023-05-29 07:36 UTC, alegrey91 commented on deployment/host-scanner.yaml
> +        image: kubescape/host-scanner:test
In order to release the e2e local tests asap I left it in "legacy" mode (we basically build the image locally and then we load it into the cluster).
In the next few days, when the pipeline to test also managed clusters will be included, I'm going to unify the way we get the image. So the pipeline will build a `test` tag that will be pushed on quay.io and then all the clusters will get the image from here: `quay.io/kubescape/host-scanner:test`

2023-05-29 07:37 UTC, alegrey91 commented on deployment/host-scanner.yaml
> +            cpu: 0.1m
I took it from [kubescape](https://github.com/kubescape/kubescape/blob/master/core/pkg/hostsensorutils/hostsensor.yaml#L47), so we can test host-scanner in the same way we deploy it on the cluster.

2023-05-30 13:34 UTC, merged