feat: add `/healthz` and `/readyz` endpoints
kubescape/host-scanner pull request #45
Opened 2023-05-10 09:40 UTC by alegrey91

## Overview
This PR provides 2 new endpoints:
* `/healthz`
* `/readyz`

to be used with **liveness** and **readiness** probes in kubernetes.

## How to Test
I provided a couple of unit-tests, one for each handler function:
```
go test -v . -run TestHealthzHandler
go test -v . -run TestReadyzHandler
```
 
## Related issues/PRs:
This PR is related to this one in **kubescape**: [1224](https://github.com/kubescape/kubescape/pull/1224).

## Checklist before requesting a review
- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [x] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

2023-05-10 09:53 UTC, matthyx commented on httphandlers.go
> +		time.Sleep(10 * time.Second)
not sure it's adequate... @dwertent ?

2023-05-10 10:11 UTC, yuleib requested changes

2023-05-10 10:11 UTC, yuleib commented on httphandlers.go
> +		io.WriteString(w, `{"ready": true}`)
Error return value of `io.WriteString` is not checked (errcheck)
--> @alegrey91 pls. add a check to test this value. if we are not expecting to receive anything just put an obj for future development without taking any action on it.

2023-05-10 10:11 UTC, yuleib commented on httphandlers.go
> +		time.Sleep(10 * time.Second)
for 10sec you mean ?

2023-05-10 10:13 UTC, yuleib requested changes

2023-05-10 10:13 UTC, yuleib commented on httphandlers.go
> +	io.WriteString(w, `{"alive": true}`)
Error return value of `io.WriteString` is not checked (errcheck)
--> @alegrey91 pls. add a check to test this value. if we are not expecting to receive anything just put an obj for future development without taking any action on it.

2023-05-10 10:48 UTC, alegrey91 commented on httphandlers.go
> +		time.Sleep(10 * time.Second)
sorry @matthyx @yuleib , I forgot to remove it.

2023-05-10 12:09 UTC, alegrey91 commented on httphandlers.go
> +		time.Sleep(10 * time.Second)
removed

2023-05-10 12:10 UTC, alegrey91 commented on httphandlers.go
> +	io.WriteString(w, `{"alive": true}`)
Updated, and replaced `io.WriteString()` with `w.Write()` function that is more appropriate.

2023-05-11 14:15 UTC, matthyx requested changes
please make sure you understand how to attach logs to otel using our logger

2023-05-11 14:15 UTC, matthyx commented on httphandlers.go
> +			Ctx(context.TODO()).
you should take context from the request (look elsewhere in the code)

2023-05-11 14:15 UTC, matthyx commented on httphandlers.go
> +			Ctx(context.Background()).
same

2023-05-11 17:03 UTC, alegrey91 commented on httphandlers.go
> +			Ctx(context.TODO()).
fixed

2023-05-11 17:03 UTC, alegrey91 commented on httphandlers.go
> +			Ctx(context.Background()).
fixed

2023-05-12 05:09 UTC, matthyx approved these changes

2023-05-12 05:12 UTC, matthyx commented
Thanks @alegrey91 !
As a follow-up PR can you remove `Ctx()` for `Info()` level logs (I saw them in several places, not only in your added code)?
The goal is to only attach abnormal logs to traces and prevent unnecessary investigations for informative logs.

2023-05-12 05:13 UTC, matthyx commented
> Thanks @alegrey91 ! As a follow-up PR can you remove `Ctx()` for `Info()` level logs (I saw them in several places, not only in your added code)? The goal is to only attach abnormal logs to traces and prevent unnecessary investigations for informative logs.

I even have a PR for that: https://github.com/kubescape/go-logger/pull/8

2023-05-12 09:25 UTC, alegrey91 commented
> Thanks @alegrey91 ! As a follow-up PR can you remove `Ctx()` for `Info()` level logs (I saw them in several places, not only in your added code)? The goal is to only attach abnormal logs to traces and prevent unnecessary investigations for informative logs.

Do you want to wait until after the go-logger PR has been merged?

2023-05-12 09:33 UTC, matthyx commented
> Do you want to wait until after the go-logger PR has been merged?

nope, go ahead

2023-05-12 09:46 UTC, merged