test: add integration test
kubescape/host-scanner pull request #48
Opened 2023-06-09 15:45 UTC by alegrey91

## Overview

2023-06-22 08:55 UTC, yuleib requested changes
Looks good @alegrey91 - well done! 
please resolve all GA comments before so the flow will not break soon 
https://github.com/kubescape/host-scanner/actions/runs/5253286317

2023-06-28 07:45 UTC, yuleib commented
@alegrey91 - is everything resolve here ? can we merge that ?

2023-06-28 09:32 UTC, alegrey91 commented
> @alegrey91 - is everything resolve here ? can we merge that ?

We are going to have some fails related to non-expected results in e2e tests.
I'm going to open an issue for that.
In the meantime we can merge it.

2023-06-28 10:34 UTC, yuleib approved these changes

2023-06-28 10:38 UTC, merged