fix(sensor): remove redundant warnings
kubescape/host-scanner pull request #52
Opened 2023-07-05 07:36 UTC by alegrey91

## Overview
This PR removes redundant logs during **cni** detection.

## Checklist before requesting a review

put an [x] in the box to get it checked 

- [x] My code follows the style guidelines of this project
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

2023-07-05 09:55 UTC, dwertent requested changes

2023-07-05 09:55 UTC, dwertent commented on e2e/controlplaneinfo_test.go
> +				fmt.Println(resultBody.PKIFiles[i].Path)
Use the Kubescape logger instead.

2023-07-05 09:55 UTC, dwertent commented on e2e/controlplaneinfo_test.go
> +			for i := range resultBody.PKIFiles {
Comment out

2023-07-05 09:55 UTC, dwertent commented on sensor/CNI.go
> +		logger.L().Warning("No CNI found")
What is the use case?

2023-07-05 11:17 UTC, alegrey91 commented on sensor/CNI.go
> +		logger.L().Warning("No CNI found")
Instead of returning all the waring for non-found CNIs, it returns only a single warning when no CNI have been found.

2023-07-05 14:45 UTC, dwertent commented on sensor/CNI.go
> +		logger.L().Warning("No CNI found")
What is the use-case for not finding CNIs? Does it happen a lot?

2023-07-05 14:53 UTC, alegrey91 commented on sensor/CNI.go
> +		logger.L().Warning("No CNI found")
really difficult, but could happen when another **cni** (not in our list) is used or even when a **cni** is not installed, but is not a common case for production clusters.

2023-07-06 06:41 UTC, dwertent commented
@alegrey91 I see many tests failed

2023-07-06 07:06 UTC, dwertent approved these changes

2023-07-06 07:06 UTC, merged