CNI permissions + small fix
kubescape/host-scanner pull request #8
Opened 2022-09-21 13:48 UTC by kooomix

- fixed "--config" param in utils.go
- Added CNI files information to kubeletsensor.go.  Getting FileInfo for all files under "/etc/cni/" and retrieving them as a list under "CNIFiles" entry.

2022-09-28 06:55 UTC, shm12 requested changes

2022-09-28 06:55 UTC, shm12 commented on sensor/kubeletsensor.go
> +	kubeletCNIConfigFolder       = "/etc/cni/"
Are you sure this is the place? What about `/etc/cni/net.d/`. And what if the user has set a custom location (via `--cni-conf-dir` in older k8s releases)?

2022-09-28 06:55 UTC, shm12 commented on sensor/kubeletsensor.go
> +	CNIFiles []*FileInfo `json:"CNIFiles,omitempty"`
Since the CNI is defined only in the master nodes, I would expect this information to be inside `ControlPlaneInfo` and not `KubeletInfo`

2022-09-28 06:55 UTC, shm12 commented on sensor/utils.go
> +	kubeConfigArgName = "--config"
This is simply incorrect

2022-10-19 05:57 UTC, kooomix commented on sensor/utils.go
> +}
Intergrated ReadDir within getCNIConfigDirFromConfig function, dropped "makeSortedFilesList".

2022-10-19 05:57 UTC, kooomix commented on sensor/containerruntime.go
> +func getContainerRuntimeProperties(containerRuntimeName string) (*containerRuntimeProperties, error) {
Merged.

2022-10-19 05:58 UTC, kooomix commented on sensor/containerruntime.go
> +func getContainerRuntime(crEndpoint string) (*ContainerRuntimeInfo, error) {
Dropped function completely.

2022-10-19 05:59 UTC, kooomix commented on sensor/kubeletsensor.go
> +	ErrCRNotFound = errors.New("failed to find Container Runtime EndPoint")
Not sure what you mean (but anyway, removed the "ErrCRNotFound")

2022-10-19 06:00 UTC, kooomix commented on sensor/kubeletsensor.go
> +	kubeletContainerRuntimeEndPoint = "--container-runtime-endpoint"
Not sure what you mean - if you're asking if these flags should be in this file, then yes, these are kubelet flags.

2022-10-19 06:01 UTC, kooomix commented on sensor/controlplanesensor.go
> +
Done. Implemeted "makeCNIConfigFilesInfo" function.

2022-10-19 06:02 UTC, kooomix commented on sensor/containerruntime.go
> +}
Added specific properties functions and dropped global variable.
Removed completely cri-docker as it is not a container runtime but a plugin that indiciates (along other params) on the running containe runtime.

2022-10-19 06:04 UTC, kooomix commented on sensor/containerruntime.go
> +		return ""
Why do you think? I want to return "" anyway, but wanted also to debug the specific case of dockershim to have "eyes" on what's happening.

2022-10-19 06:07 UTC, kooomix commented on sensor/containerruntime.go
> +	}
re-structured CNIConfigDirFromKubelet (for a different reason, which also solved this)

2022-10-19 06:09 UTC, kooomix commented on sensor/containerruntime.go
> +}
Hope it's cleared now.
I want to keep this messages, again, to have "eyes" on whats happening.

2022-10-19 06:09 UTC, kooomix commented on sensor/containerruntime.go
> +func (cr *ContainerRuntimeInfo) getArgFromProcess(argName string) string {
functions dropped.

2022-10-19 06:11 UTC, kooomix commented on sensor/containerruntime.go
> +		zap.L().Debug("getCNIConfigDirFromConfig - found cni paths in configs for container runtime",
done

2022-10-19 06:11 UTC, kooomix commented on sensor/containerruntime.go
> +// 4. Extract CNI config dur from config through a custom function of the Container Runtime. If not found, return empty string
Fixed manually.

2022-10-19 06:11 UTC, kooomix commented on sensor/containerruntime.go
> +// 3. return defaults
fixed manually

2022-10-19 06:12 UTC, kooomix commented on sensor/containerruntime.go
> +func (cr *ContainerRuntimeInfo) updateCNIConfigDir() {
done

2022-10-19 07:40 UTC, shm12 commented on sensor/kubeletsensor.go
> +	ErrCRNotFound = errors.New("failed to find Container Runtime EndPoint")
I mean, those variables are related to the container runtime file. This is the kubelet *sensor*, so even though they are related to kubelet, this is not their place.

2022-10-19 07:40 UTC, shm12 commented on sensor/kubeletsensor.go
> +	kubeletContainerRuntimeEndPoint = "--container-runtime-endpoint"
Same

2022-10-19 08:01 UTC, shm12 commented on sensor/controlplanesensor.go
>  	}
Great!

2022-10-19 08:02 UTC, shm12 commented on sensor/kubeletsensor.go
> +	kubeletCNIConfigDir             = "--cni-conf-dir"
I still think this isn't the place for these variables

2022-10-19 08:05 UTC, kooomix commented on sensor/kubeletsensor.go
> +	kubeletContainerRuntimeEndPoint = "--container-runtime-endpoint"
Well, logically, can be in both. Anyway, made the change.

2022-10-19 08:12 UTC, shm12 commented on sensor/containerruntime.go
> +	CNIConfigDir, _ := proc.GetArg(kubeletCNIConfigDir)
Please check also the kubelet config file

2022-10-19 08:29 UTC, kooomix commented on sensor/containerruntime.go
> +	default:
docker is actually containerd, which is already handled...
Do you think we should have containerd as default, in case an unknown CRIKind was sent?

2022-10-19 08:36 UTC, kooomix commented on sensor/kubeletsensor.go
> +	kubeletCNIConfigDir             = "--cni-conf-dir"
moved.

2022-10-19 08:38 UTC, kooomix commented on sensor/containerruntime.go
> +func getContainerRuntimeFromProcess() (*ContainerRuntimeInfo, error) {
This is what we do in getCNIConfigPath - we first check runtime (CNIConfigDirFromKubelet) and onlt them the process.

2022-10-19 08:58 UTC, kooomix commented on sensor/containerruntime.go
> +	CNIConfigDir, _ := proc.GetArg(kubeletCNIConfigDir)
From docs:
"Prior to Kubernetes 1.24, the CNI plugins could also be managed by the kubelet using the cni-bin-dir and network-plugin command-line parameters. These command-line parameters were removed in Kubernetes 1.24, with management of the CNI no longer in scope for kubelet."

So I'm not sure it's worth the effort (I added the kubeletCNIConfigDir just because it was quite easy.

BTW, out of curiosity - did you encounter how exactly the cni config path is stored in the kubelet config?

2022-10-19 09:11 UTC, kooomix commented on sensor/containerruntime.go
> +func getContainerRuntimeFromProcess() (*ContainerRuntimeInfo, error) {
And then newContainerRuntime is already doing the detection, I don't want to take out the detection out of the constructor.

2022-10-19 12:16 UTC, shm12 commented on sensor/containerruntime.go
> +	CNIConfigDir, _ := proc.GetArg(kubeletCNIConfigDir)
I was talking about the container runtime parameter. My mistake

2022-10-19 12:23 UTC, shm12 commented on sensor/containerruntime.go
> +func getContainerRuntimeFromProcess() (*ContainerRuntimeInfo, error) {
What you are doing to detect the CRI in `getContainerRuntimeFromProcess` is try and error. What I was suggesting is to first detect the CRI (by looking at what processes are running) and then call `newContainerRuntime` only once with the right parameter

2022-10-19 12:47 UTC, kooomix commented on sensor/containerruntime.go
> +	CNIConfigDir, _ := proc.GetArg(kubeletCNIConfigDir)
I'm familiar with this doc, couldn't identify cni configuration.
I'm already looking at the container runtime parameter, this is the main path of search (that is now mandatory for the user to configure).

Resolved?

2022-10-19 12:51 UTC, kooomix commented on sensor/containerruntime.go
> +func getContainerRuntimeFromProcess() (*ContainerRuntimeInfo, error) {
I don't really see what exactly you want to achieve by that, it will only add uneeded complexity. We support only 2 container runtimes which we already know their process suffixes and other parameters, so try and error would be the best path IMO, unless i'm missing something here.

2022-10-19 13:21 UTC, shm12 approved these changes

2022-10-19 13:58 UTC, merged